"""init

Revision ID: 329a43a2dde7
Revises: 
Create Date: 2024-01-08 15:57:41.242929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329a43a2dde7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('auth_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('captcha_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('time_limit_action', sa.String(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.guild_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captcha_settings')
    op.drop_table('auth_requests')
    op.drop_table('guild')
    # ### end Alembic commands ###
